# Generated by Django 5.0.6 on 2024-07-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='Detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Gender',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicine_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
