# Generated by Django 5.0.6 on 2024-07-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_age_patient_detail_patient_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Detail',
            new_name='detail',
        ),
    ]
