# Generated by Django 5.0.6 on 2024-07-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_age_patient_age_remove_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
